// data/surahs.js
const surahs = [
    { name: "Al Fatihah", verseCount: 7 },
    { name: "Al Baqarah", verseCount: 286 },
    { name: "Ali Imran", verseCount: 200 },
    { name: "An Nisa", verseCount: 176 },
    { name: "Al Ma'idah", verseCount: 120 },
    { name: "Al An'am", verseCount: 165 },
    { name: "Al A'raf", verseCount: 206 },
    { name: "Al Anfal", verseCount: 75 },
    { name: "At Taubah", verseCount: 129 },
    { name: "Yunus", verseCount: 109 },
    { name: "Hud", verseCount: 123 },
    { name: "Yusuf", verseCount: 111 },
    { name: "Ar Ra'd", verseCount: 43 },
    { name: "Ibrahim", verseCount: 52 },
    { name: "Al Hijr", verseCount: 99 },
    { name: "An Nahl", verseCount: 128 },
    { name: "Al Isra", verseCount: 111 },
    { name: "Al Kahf", verseCount: 110 },
    { name: "Maryam", verseCount: 98 },
    { name: "Ta Ha", verseCount: 135 },
    { name: "Al Anbiya", verseCount: 112 },
    { name: "Al Hajj", verseCount: 78 },
    { name: "Al Mu'minun", verseCount: 118 },
    { name: "An Nur", verseCount: 64 },
    { name: "Al Furqan", verseCount: 77 },
    { name: "Asy Syu'ara", verseCount: 227 },
    { name: "An Naml", verseCount: 93 },
    { name: "Al Qasas", verseCount: 88 },
    { name: "Al 'Ankabut", verseCount: 69 },
    { name: "Ar Rum", verseCount: 60 },
    { name: "Luqman", verseCount: 34 },
    { name: "As Sajdah", verseCount: 30 },
    { name: "Al Ahzab", verseCount: 73 },
    { name: "Saba", verseCount: 54 },
    { name: "Fatir", verseCount: 45 },
    { name: "Ya Sin", verseCount: 83 },
    { name: "As Saffat", verseCount: 182 },
    { name: "Sad", verseCount: 88 },
    { name: "Az Zumar", verseCount: 75 },
    { name: "Ghafir", verseCount: 85 },
    { name: "Fussilat", verseCount: 54 },
    { name: "Asy Syura", verseCount: 53 },
    { name: "Az Zukhruf", verseCount: 89 },
    { name: "Ad Dukhan", verseCount: 59 },
    { name: "Al Jasiyah", verseCount: 37 },
    { name: "Al Ahqaf", verseCount: 45 },
    { name: "Muhammad", verseCount: 38 },
    { name: "Al Fath", verseCount: 29 },
    { name: "Al Hujurat", verseCount: 18 },
    { name: "Qaf", verseCount: 45 },
    { name: "Az Zariyat", verseCount: 60 },
    { name: "At Tur", verseCount: 49 },
    { name: "An Najm", verseCount: 62 },
    { name: "Al Qamar", verseCount: 55 },
    { name: "Ar Rahman", verseCount: 78 },
    { name: "Al Waqi'ah", verseCount: 96 },
    { name: "Al Hadid", verseCount: 29 },
    { name: "Al Mujadilah", verseCount: 22 },
    { name: "Al Hasyr", verseCount: 24 },
    { name: "Al Mumtahanah", verseCount: 13 },
    { name: "As Saff", verseCount: 14 },
    { name: "Al Jumu'ah", verseCount: 11 },
    { name: "Al Munafiqun", verseCount: 11 },
    { name: "At Tagabun", verseCount: 18 },
    { name: "At Talaq", verseCount: 12 },
    { name: "At Tahrim", verseCount: 12 },
    { name: "Al Mulk", verseCount: 30 },
    { name: "Al Qalam", verseCount: 52 },
    { name: "Al Haqqah", verseCount: 52 },
    { name: "Al Ma'arij", verseCount: 44 },
    { name: "Nuh", verseCount: 28 },
    { name: "Al Jinn", verseCount: 28 },
    { name: "Al Muzzammil", verseCount: 20 },
    { name: "Al Muddassir", verseCount: 56 },
    { name: "Al Qiyamah", verseCount: 40 },
    { name: "Al Insan", verseCount: 31 },
    { name: "Al Mursalat", verseCount: 50 },
    { name: "An Naba", verseCount: 40 },
    { name: "An Nazi'at", verseCount: 46 },
    { name: "'Abasa", verseCount: 42 },
    { name: "At Takwir", verseCount: 29 },
    { name: "Al Infitar", verseCount: 19 },
    { name: "Al Mutaffifin", verseCount: 36 },
    { name: "Al Insyiqaq", verseCount: 25 },
    { name: "Al Buruj", verseCount: 22 },
    { name: "At Tariq", verseCount: 17 },
    { name: "Al A'la", verseCount: 19 },
    { name: "Al Gasyiyah", verseCount: 26 },
    { name: "Al Fajr", verseCount: 30 },
    { name: "Al Balad", verseCount: 20 },
    { name: "Asy Syams", verseCount: 15 },
    { name: "Al Lail", verseCount: 21 },
    { name: "Ad Duha", verseCount: 11 },
    { name: "Al Insyirah", verseCount: 8 },
    { name: "At Tin", verseCount: 8 },
    { name: "Al 'Alaq", verseCount: 19 },
    { name: "Al Qadr", verseCount: 5 },
    { name: "Al Bayyinah", verseCount: 8 },
    { name: "Az Zalzalah", verseCount: 8 },
    { name: "Al 'Adiyat", verseCount: 11 },
    { name: "Al Qari'ah", verseCount: 11 },
    { name: "At Takasur", verseCount: 8 },
    { name: "Al 'Asr", verseCount: 3 },
    { name: "Al Humazah", verseCount: 9 },
    { name: "Al Fil", verseCount: 5 },
    { name: "Quraisy", verseCount: 4 },
    { name: "Al Ma'un", verseCount: 7 },
    { name: "Al Kautsar", verseCount: 3 },
    { name: "Al Kafirun", verseCount: 6 },
    { name: "An Nasr", verseCount: 3 },
    { name: "Al Lahab", verseCount: 5 },
    { name: "Al Ikhlas", verseCount: 4 },
    { name: "Al Falaq", verseCount: 5 },
    { name: "An Nas", verseCount: 6 }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = surahs;
}